//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListNPL
    {
        public int IDList { get; set; }
        public int IDDH { get; set; }
        public int IDNPL { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual NPL NPL { get; set; }
    }
}
